### ISSUE TITLE
Can not paste into "Folder" field in "Connection settings"

### ISSUE THREAD

**Issue by nicolas-raoul** [fastogt/fastonosql#13]
On Ubuntu 2016.04 with 1.0.0.0

- CTRL-V does not work
- Right-click -> "Paste" does not work
- Middle-click does not work

On the opposite, pasting into the connection name or command line parameters field works perfectly.

**Comment by topilski** [comment]
Hi "Folder" field only for UI displaying, all connection parameters installed via "Command line field". I next releases i rename this label sorry for UI confusing.
