### ISSUE TITLE
Command line parameters not saved correctly by "Connection Settings" dialog

### ISSUE THREAD

**Issue by nicolas-raoul** [fastogt/fastonosql#14]
On Ubuntu 2016.04 with 1.0.0.0
Steps to reproduce:

1) Create a new Leveldb connection
2) Go to the command line parameters field
3) Enter `-f /home/nico/.config/chromium/Default/Local\ Extension\ Settings/ncdlagniojmheiklojdcpdaeepochckl -d \n -ns :`
4) Save and close
5) Reopen
6) The field's value has become `-f /home/nico/.config/chromium/Default/Local -d \n -ns :`

The path also gets corrupted when using `"` quotes instead of backslashes.

**Comment by topilski** [comment]
Hi, like hotfix you can use quotes something like this: '/home/nico/.config/chromium/Default/Local\ Extension\ Settings/ncdlagniojmheiklojdcpdaeepochckl' but for UI useful behavior i think need add more fields where user can select folder via dialog.

**Comment by nicolas-raoul** [comment]
Thanks for the tip of the single quotes!
They get removed next time you open the dialog, though.

**Comment by topilski** [comment]
Fixed in version 1.1.0 please check behavior and close issue if work as needed.

**Comment by topilski** [comment]
ping
