### ISSUE TITLE
LOCK: No such file or directory

### ISSUE THREAD

**Issue by nicolas-raoul** [fastogt/fastonosql#16]
I am trying to connect to LevelDB with `-f '/home/nico/.config/chromium/Default/Local\ Extension\ Settings/ncdlagniojmheiklojdcpdaeepochckl/000100.ldb' -d \n -ns :`

I get: `Fail connect to server: IO error: /home/nico/.config/chromium/Default/Local/ Extension/ Settings/ncdlagniojmheiklojdcpdaeepochckl//LOCK: No such file or directory!`

Even though `/home/nico/.config/chromium/Default/Local Extension Settings/ncdlagniojmheiklojdcpdaeepochckl/LOCK` exists.
Am I doing something wrong?
Levelup (the Nodejs library) has no problem connecting to the same path.

`-f '/home/nico/.config/chromium/Default/Local\ Extension\ Settings/ncdlagniojmheiklojdcpdaeepochckl' -d \n -ns :` does not work either and says `Fail connect to server: IO error: /home/nico/.config/chromium/Default/Local/ Extension/ Settings//LOCK: No such file or directory!`

**Comment by topilski** [comment]
Seams FastoNoSQL can't open directory. I will try to reproduce. Thx

**Comment by topilski** [comment]
do something like this cp -r /home/sasha/.config/chromium/Default/Local\ Extension\ Settings/pgjjikdiikihdfpoppgaidccahalehjh/ /home/sasha/2

cmd line is -f /home/sasha/2 -d \n -ns : -c
![ch](https://cloud.githubusercontent.com/assets/4686379/20166780/24eebe64-a6e5-11e6-9731-229e347787a8.png)

spaces will be fixed sorry for this issue

**Comment by topilski** [comment]
Fixed in version 1.1.0 please check behavior and close issue if work as needed.

**Comment by topilski** [comment]
ping
