### ISSUE TITLE
Mac crashes with ssh tunnel to Redis

### ISSUE THREAD

**Issue by Alexand** [fastogt/fastonosql#17]
I'm trying to connect a Redis instance through ssh tunnel and Public/Private key.

The app quits unexpectedly in below situations:

* I fill all the data for creating a new connection then I click "Test".
or
* I fill all the data, save the connection and then try to connect to the newly created connection.

So, basically, when it tries to connect.

**Mac OS X 10.11.4  -  MacBook Pro (Retina, 13-inch, Mid 2014)**

**Comment by topilski** [comment]
Hi thank you for issue, try to reproduce.

**Comment by topilski** [comment]
@Alexand which version of FastoNoSQL you used?

**Comment by topilski** [comment]
Reproduced, will be fixed!

**Comment by topilski** [comment]
Fixed in 1.2.0 version, please download it and if work as needed close this issue, thx!

**Comment by topilski** [comment]
ping
