### ISSUE TITLE
add more support of appearance

### ISSUE THREAD

**Issue by softwarevamp** [fastogt/fastonosql#18]
add more support of appearance
eg, font-size, color, ...

**Comment by topilski** [comment]
Hi @softwarevamp font-size you can change in preferences. What you mean color?

**Comment by softwarevamp** [comment]
I want to change the font-size.

**Comment by topilski** [comment]
Sure, will try to implement

**Comment by topilski** [comment]
Please update version, now you can change font size!

**Comment by softwarevamp** [comment]
Great! thanks, i now choose Segoe UI 9px as my default font. it looks nice.
![image](https://cloud.githubusercontent.com/assets/746953/21575132/27f148e0-ced9-11e6-92e6-a02b281c69a7.png)

**Comment by topilski** [comment]
You are welcome!
