### ISSUE TITLE
failled to load xcb plugin

### ISSUE THREAD

**Issue by ilia987** [fastogt/fastonosql#19]
installed latest version on ubuntu, and got the error:

```
QFactoryLoader::QFactoryLoader() checking directory path "/opt/fastonosql/lib/platforms" ...
QFactoryLoader::QFactoryLoader() looking at "/opt/fastonosql/lib/platforms/libqxcb.so"
Found metadata in lib /opt/fastonosql/lib/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 329472
}


Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/opt/fastonosql/bin/platforms" ...
loaded library "/opt/fastonosql/lib/platforms/libqxcb.so"
QLibraryPrivate::loadPlugin failed on "/opt/fastonosql/lib/platforms/libqxcb.so" : "Cannot load library /opt/fastonosql/lib/platforms/libqxcb.so: (/usr/lib/x86_64-linux-gnu/libQt5DBus.so.5: version `Qt_5' not found (required by /opt/fastonosql/bin/../lib/libQt5XcbQpa.so.5))"
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
/usr/bin/fastonosql: line 14: 10492 Aborted                 (core dumped) "$SOURCE_DIR/FastoNoSQL"

```

**Comment by topilski** [comment]
Hi @ilia987 which architecture of your device?

**Comment by ilia987** [comment]
`Linux dev1 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by topilski** [comment]
thx, i will try to fix

**Comment by topilski** [comment]
Can you execute command: ldd /opt/fastonosqlo/bin/FastoNoSQL ?

**Comment by ilia987** [comment]
mintor mistake the command is 
`ldd /opt/fastonosql/bin/FastoNoSQL`
output
`inux-vdso.so.1 =>  (0x00007fff04db4000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ffe0d953000)
	libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007ffe0d738000)
	libQt5Widgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00007ffe0cf0e000)
	libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007ffe0c8c1000)
	libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007ffe0c21b000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ffe0bffc000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ffe0bcf8000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ffe0b9f2000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ffe0b7db000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ffe0b416000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007ffe0b20e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ffe0db6d000)
	libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007ffe0afbc000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007ffe0acb4000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007ffe0a97f000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007ffe0a758000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007ffe0a503000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007ffe0a2ea000)
	libGL.so.1 => /usr/lib/nvidia-352/libGL.so.1 (0x00007ffe09fb9000)
	libicui18n.so.52 => /usr/lib/x86_64-linux-gnu/libicui18n.so.52 (0x00007ffe09bb2000)
	libicuuc.so.52 => /usr/lib/x86_64-linux-gnu/libicuuc.so.52 (0x00007ffe09839000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007ffe09630000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007ffe093f2000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007ffe091d2000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007ffe08f2f000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007ffe08d13000)
	libnvidia-tls.so.352.93 => /usr/lib/nvidia-352/tls/libnvidia-tls.so.352.93 (0x00007ffe08b0f000)
	libnvidia-glcore.so.352.93 => /usr/lib/nvidia-352/libnvidia-glcore.so.352.93 (0x00007ffe0607b000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007ffe05e69000)
	libicudata.so.52 => /usr/lib/x86_64-linux-gnu/libicudata.so.52 (0x00007ffe045fb000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007ffe043f7000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007ffe041f1000)`

**Comment by topilski** [comment]
You started FastoNoSQL via sh file? `/opt/fastonosql/bin/fastonosql.sh`

**Comment by ilia987** [comment]
i have tried via shell , and directly and some other combinations. i have tried it on another pc, have similar error
##error output start##
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
/usr/bin/fastonosql: line 14:  6139 Aborted                 (core dumped) "$SOURCE_DIR/FastoNoSQL"

##error output end##


but i cant locate the core dump

**Comment by topilski** [comment]
Can you copy /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5 to /opt/fastonosql/lib and try again to start application.

**Comment by ilia987** [comment]
Cannot mix incompatible Qt library (version 0x50201) with this library (version 0x50700)

can you provide a version with qt staticly linked?

**Comment by topilski** [comment]
No it will broke license, i prepare new release version 1.4.1 it takes me about 1 hour.

**Comment by ilia987** [comment]
ok, ill give it a try and post an update here

**Comment by ilia987** [comment]
i have another issue with building from source, after you will post commit for 1.4.1 ill try to build if it will fail ill post an issue

**Comment by topilski** [comment]
It wiil be cool! I like new issues!

**Comment by topilski** [comment]
Please try this : http://fastonosql.com/download_p?platform=linux&filename=fastonosql-1.4.1-x86_64.deb

**Comment by ilia987** [comment]
working.
but you have wrong display at the popup
"you are using the latest version (1.4.0.0 )"

**Comment by topilski** [comment]
Fixed, thank you!
