### ISSUE TITLE
memcached connection fails with UNKNOWN READ

### ISSUE THREAD

**Issue by felixbuenemann** [fastogt/fastonosql#2]
System: Mac OS X 10.11.1
Version: FastoNoSQL 0.5.5
memcached 1.4.24 (installed via homebrew)

When trying to create/test connection to with parameters `-h 127.0.0.1 -p 11211 -d \n` I get the following error:
```
Connection state: Couldn't ping server: UKNOWN READ
```

I can talk to the server just fine using `nc 127.0.0.1 11211`.

**Comment by topilski** [comment]
Good day, seems like bug, try to reproduce and fix it thx.

**Comment by topilski** [comment]
Fixed, please specify your email and i send you fixed version.

**Comment by felixbuenemann** [comment]
Thanks, my Email is listed on my [Github Profile](https://github.com/felixbuenemann).

**Comment by topilski** [comment]
I sent, please verify behavior and if issue not reproduced please close it.

**Comment by felixbuenemann** [comment]
Thanks it works now, but loading keys fails, I think because FastoNoSQL sends UPPERCASE commands, but memcached wants lowercase:
```
STATS ITEMS
ERROR
stats items
STAT items:1:number 1
STAT items:1:age 231
…
END
```

**Comment by topilski** [comment]
Please create issue, i try to fix it!
