### ISSUE TITLE
any tutorials for beginners? lmdb on ubuntu

### ISSUE THREAD

**Issue by kumrzz** [fastogt/fastonosql#21]
are there any beginner tutorials out there on how to use fastonosql? I am trying to open a lmdb file (data.mdb+lock.mdb) which is password-protected, in ubuntu.

when I try connecting, I get the below, how do I pass login parameters?
`16:32:29.097: Fail open database: Permission denied`

I tried running command `INFO` and got:
`16:30:55.818: Invalid input argument for command: 'INFO', passed 0 arguments, must be in range 1 - 1.`

**Comment by topilski** [comment]
Hi @kumrzz , you can use this page: http://fastonosql.com/help but it is only for redis. For lmdb please specify folder of files.

**Comment by topilski** [comment]
Folder for files  (data.mdb+lock.mdb)

**Comment by kumrzz** [comment]
hi @topilski that only contains two gifs, which I have already followed: I have already opened the file in question by specifying the folder and using the test button(was successful) ... only after I connect do I see what I posted. So I was looking for a more detailed guide, ideally with a list of usable commands, syntax etc.

**Comment by topilski** [comment]
Hi @kumrzz for lmdb we support next command https://github.com/fastogt/fastonosql/blob/master/src/core/db/lmdb/internal/commands_api.h ,  `SET key value GET key value DEL key value` this command will work for all databases. Sorry but for lmdb i we can't have some tutorial, also some tests of db you can find here https://github.com/fastogt/fastonosql/blob/master/tests/mock_tests/test_connections.cpp

**Comment by topilski** [comment]
You are welcome!
