### ISSUE TITLE
Memcached won't show object values

### ISSUE THREAD

**Issue by yingtho** [fastogt/fastonosql#22]
It can show the keys but when trying to load keys which is object data the logs says:
15:24:37.426: Get function error: NOT FOUND

![screen shot 2017-03-01 at 15 20 49](https://cloud.githubusercontent.com/assets/4170913/23463692/c6b7bc00-fe92-11e6-9e5e-3a7ef541506c.png)

**Comment by topilski** [comment]
Hi @yingtho may be keys was deleted from other application?

**Comment by yingtho** [comment]
No it was just created when i try to look into it. If I create a simple key (string) and that persist fine (the test key above). The editor won't allow creation of objects only simple objects.

**Comment by topilski** [comment]
Which types you want to create? Also check ttl values on your keys.

**Comment by yingtho** [comment]
Well, it working but it seems that sometime its the cached keys i see.
