### ISSUE TITLE
Does not work with Chrome IndexedDB files?

### ISSUE THREAD

**Issue by bman654** [fastogt/fastonosql#24]
Hi,

I tried to use this to open some leveldb files used by Chrome's indexedb.  I get this error when I try to "connect" to the leveldb folder:

```
13:06:09.747: Fail connect to server: Invalid argument: idb_cmp1 does not match existing comparator : leveldb.BytewiseComparator!
```

Anyway to fix that?

**Comment by topilski** [comment]
Hi @bman654 , you right now not working with IndexedDB, need to implement comparator something like this: https://cs.chromium.org/chromium/src/content/browser/indexed_db/indexed_db_leveldb_coding.cc?sq=package:chromium&type=cs&l=880

**Comment by topilski** [comment]
Implemented IndexedDB support, keys can be in binary formats, we hexed it for displaying, but in current moment impossible receive value by key.

**Comment by topilski** [comment]
Fixed value receive routine.

**Comment by AntonKukoba1** [comment]
Trying to open chrome's leveldb via fastonosql v1.16.3.0 windows 10 x64
`14:45:00.732: Fail connect to server: Invalid argument: idb_cmp1 does not match existing comparator : leveldb.BytewiseComparator!`

**Comment by topilski** [comment]
Hi, please change comparator in settings.

**Comment by topilski** [comment]
Hi @AntonKukoba1 , did you try to change comparator in settings, which result you have?

**Comment by AntonKukoba1** [comment]
Yep changing the comparator in the Connection settings helps to open the database, though this doesn't help with the data representation, keys and values are all binary. For values there's at least a way to show it as various formats, but the keys are always hex...

**Comment by topilski** [comment]
May be keys/values should be binaries? Which commands you using for write this items?

**Comment by topilski** [comment]
Also try to play with compression.

**Comment by CaledoniaProject** [comment]
It won't work, you will have to implement native V8 deserializer and key decoder.
