### ISSUE TITLE
Improve search under explorer tree 

### ISSUE THREAD

**Issue by tburschka** [fastogt/fastonosql#25]
The search under the explorer tree seems to be not working (as intended).
I try to seach one ore more keys with a specific part of a name but the search/filter isn't even matching the simple rules like searching for "category" (see screenshot) would be filter any results. even starting with "kv:" will filter anything. The filter should be a regexp ('/category/') search or a like ("%category%") search on any keys in any open storage. 

![fastonosql_search](https://cloud.githubusercontent.com/assets/300583/24283091/f5987b12-1063-11e7-96f9-aafbd50be347.png)

**Comment by topilski** [comment]
Filter working as expected, can you test behavior on current release?

**Comment by topilski** [comment]
ping

**Comment by tburschka** [comment]
Sry, didn't see the first message. I will try this evening.

**Comment by topilski** [comment]
Sure, thank you!
