### ISSUE TITLE
UI/Usage improvements

### ISSUE THREAD

**Issue by tburschka** [fastogt/fastonosql#27]
Hi, i like this tool much, but it could be improved in some ways.

In a default use case i connect to an existing instance, select a database and filter with the search the available keys.

For that i have currenty use the submenu "Recent connections" under file, it would be slightly easier if the recent connections would be a list direct (eg. 5-10 recent connections and the "clear recent connections" button under file (and maybe you sould call the "file" entry  "connection" instead).

After i select a connection the connection currently has to be manual by right click on the entry with ("connect/disconnect). It would be better if the selected connection (opened via recent connections/connection manager) connected automatically - this could be an global option or an choice on the connection entry. An double-click on the entry should do be open the connection as well.

The next step is to load an available database. Currently you need to click "Load content of the database". It would be better if the content is loaded completely by default on an double-click on the entry. If it is an huge database you can use the current process with the "Load content of the database" dialog.

**Comment by topilski** [comment]
Hi, thank you for your issues i will try to implement it.

**Comment by topilski** [comment]
Hi @tburschka, i think request  (
For that i have currenty use the submenu "Recent connections" under file, it would be slightly easier if the recent connections would be a list direct (eg. 5-10 recent connections and the "clear recent connections" button under file (and maybe you sould call the "file" entry "connection" instead).  ) implemented in current solution it is not a good solution when menu have a huge menu, i divide this functionality into submenu.

request (After i select a connection the connection currently has to be manual by right click on the entry with ("connect/disconnect). It would be better if the selected connection (opened via recent connections/connection manager) connected automatically - this could be an global option or an choice on the connection entry. An double-click on the entry should do be open the connection as well.) implemented, in preference dialog i place "Auto connection db" checkbox.

**Comment by tburschka** [comment]
> implemented in current version, this is not a good idea when menu have a huge amount items, i divide this functionality into submenu.

Maybe you're right, on lower resolution screens it might be to large. maybe the decition if a submenu is required should be depend on the screen size. In my case it souldn't take more than 25% of the screen heigh even with 10 items.

> implemented, in preference dialog i placed "Auto connection db" checkbox. In next versions you can test this functionality.

Thank you, i will test with pleasure
