### ISSUE TITLE
The Windows Error Reporting GUI fails to appear when FastoNoSQL crashes

### ISSUE THREAD

**Issue by unforgettableid** [fastogt/fastonosql#28]
Hi! I'm using FastoNoSQL 1.5.0 on Windows 10 Home version 1607 (build 14393.953).

Every time I start it, it crashes silently, even before it creates a `fastonosql.log` file.

# Expected results

I was expecting to see this dialog box:

**FastoNoSQL has stopped working.**
Windows can check online for a solution to the problem.
[ -> Check online for a solution and close the program ]
[ -> Close the program ]

# Actual results

Nothing. Windows Error Reporting doesn't show any dialog box, and Windows in fact gives no hint that FastoNoSQL crashed at all. The only thing that happens is that a new problem report appears under "FastoNoSQL" in the Problem Reports control panel.

# More details

Sysinternals Process Monitor reports that something starts "C:\WINDOWS\system32\WerFault.exe", and that WerFault.exe does write a minidump to my AppData\Local folder. But still, no Windows Error Reporting dialog box appears.

Thanks for reading this!

**Comment by topilski** [comment]
Hi all, thank you for helping in this issue, i have update our build server and now started from FastoNoSQL 1.8.2 application should work as expected, please check i'am waiting for yours feedbacks.

**Comment by topilski** [comment]
ping
