### ISSUE TITLE
FastoNoSQL silently fails to launch, because it mistakenly assumes my CPU supports AVX

### ISSUE THREAD

**Issue by unforgettableid** [fastogt/fastonosql#29]
Hi! I'm using FastoNoSQL 1.5.0 for x64 on Windows 10 Home version 1607 (build 14393.953).

Every time I start FastoNoSQL, it crashes silently, even before it creates a `fastonosql.log` file.

So there are two problems.

A) It crashes silently when it really should show a Windows Error Reporting dialog box. This is bug #28.
B) It crashes, even though it shouldn't crash at all. This is the current bug. Let me explain.

WinDbg reports:

> FAILED_INSTRUCTION_ADDRESS: 
> FastoNoSQL!unqlite_util_random_num+5f8a4d
> 00000000`00e57bad c5fb1045b8      vmovsd  xmm0,qword ptr [rbp-48h]

Well, VMOVSD is an AVX (Advanced Vector Extensions) instruction. I'm using a cheap entry-level CPU: a quad-core Intel Pentium N3540. It doesn't support AVX instructions.

What compiler command line was used to compile unqlite?

Thanks for reading!

**Comment by unforgettableid** [comment]
The 32-bit version works fine on my CPU, but it's still a bug that the 64-bit version crashes without telling me that it doesn't support my CPU.

It would be better if you would compile it to work on _all_ modern 64-bit CPUs, even cheap low-end ones. :)

Still, thank you for writing FastoNoSQL!

**Comment by topilski** [comment]
Hi thank you for your issue, i will try to fix this crash.

**Comment by raygray** [comment]
Bump. Same problem with latest version. 1.81 for x64 on Windows 10.

**Comment by topilski** [comment]
Hi @raygray , can you show me logs(placed in home folder)

**Comment by raygray** [comment]
Hi @topilski, there is no fastonosql.log created at all - application crashes silently on start-up.

Problem Details:

>
> Description
> Faulting Application Path:	C:\Program Files\FastoNoSQL\FastoNoSQL.exe
> 
> Problem signature
> Problem Event Name:	APPCRASH
> Application Name:	FastoNoSQL.exe
> Application Version:	1.8.1.0
> Application Timestamp:	00000000
> Fault Module Name:	FastoNoSQL.exe
> Fault Module Version:	1.8.1.0
> Fault Module Timestamp:	00000000
> Exception Code:	c000001d
> Exception Offset:	0000000000456533
> OS Version:	10.0.15063.2.0.0.256.48
> Locale ID:	1033
> Additional Information 1:	df44
> Additional Information 2:	df44772e4968eee96f65b5a9022fa0ee
> Additional Information 3:	c03d
> Additional Information 4:	c03d2339a36b6ff540dda1b66ca0a61d
> 
> Extra information about the problem
> Bucket ID:	f1f015a42f4cffa5082a262ff15afb5e (120836135559)

**Comment by topilski** [comment]
Hi @raygray , can you specify your email address i will send you debug version, it can give us more information about crash. Also did you try FastoRedis?

**Comment by raygray** [comment]
Hi @topilski, FastoRedis starts normally. Email address is on my profile.

**Comment by topilski** [comment]
Hi @raygray , email sent, please try to start application.

**Comment by raygray** [comment]
Same problem as before.

**Comment by topilski** [comment]
Do you have crash info?

**Comment by topilski** [comment]
Hi all, thank you for helping in this issue, i have update our build server and now started from FastoNoSQL 1.8.2 application should work as expected, please check i'am waiting for yours feedbacks.

**Comment by topilski** [comment]
ping

**Comment by unforgettableid** [comment]
Thank you very much for working to fix this issue!

It might be tricky for me to test the newest version of FastoNoSQL to make sure that the problem is fixed:  I have limited or no access to the computer which I was using.

Maybe @raygray can test.  Maybe not.

Otherwise, if nobody else complains, maybe that means that the problem is fixed.  :)
