### ISSUE TITLE
Can't save connection setting for memcached. 

### ISSUE THREAD

**Issue by kodamashi** [fastogt/fastonosql#31]
[related issue](https://github.com/fastogt/fastonosql/issues/11)
Version : 1.5.1.0  Revision : fbde4f4

I can't save connection setting for memcached.
This is reproduce procedure.

1. add connection for memcached 
2. modify host name and port 
    localhost:11211 => foo.com:11212
3. push save button
4. push open button and connect to memcached(foo.com:11212)
5. close FastoNoSQL
6 open FastoNoSQL again.
7 file->open open connection
   setting is back to localhost:11211

Regards

**Comment by topilski** [comment]
Hi, thank you for issue will try to reproduce.

**Comment by topilski** [comment]
Reproduced

**Comment by topilski** [comment]
Fixed, in next release or in master you can test it.
