### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by IMcD23** [fastogt/fastonosql#34]
It appears that the server hosting http://fastonosql.com is down, or misconfigured. It's throwing a 500 server error.

Please consider hosting the release on GitHub as well, so if your server goes down, people can still download it.

Thanks!

**Comment by topilski** [comment]
Fixed! thank you!

**Comment by topilski** [comment]
i'am not super developer on node.js express log was: 
```
GET /download_p?platform=linux&filename=fastonosql-1.5.1-x86_64.tar.gz 200 107.283 ms - 16688
GET /design/js/'%20+%20shot.image_url%20+%20' 404 8.800 ms - 61
Killed
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by IMcD23** [comment]
Doesn't show much information about why it was killed. Nevertheless, nodemon needs to be set up to restart if the process crashes or is killed, that way your site doesn't go down if there is an issue. Also, I'd recommend pingdom.com to get alerts about your sites going down.

**Comment by topilski** [comment]
Cool thank you! will try

**Comment by topilski** [comment]
Sources of fastonosql site also open source you can review it, may be you can find why it happend? sources here: https://github.com/fastogt/fastotv_site

**Comment by topilski** [comment]
How i should start nodemon? Now i opening screen and start nodemon application, this is normally? How to setup auto start nodemon if something went wrong?

**Comment by IMcD23** [comment]
Sorry, I don't have a lot of time to debug this. Just wanted to report that the site was down 😄

Nodemon will monitor your files for changes and restart the server. Looks like you might want to use something like [forever](http://www.nikola-breznjak.com/blog/javascript/nodejs/keep-your-node-js-scripts-running-with-forever-and-nodemon/) or [PM2](http://pm2.keymetrics.io) to keep it alive if it crashes.

**Comment by topilski** [comment]
Sure i understand, thank you for your help!

**Comment by topilski** [comment]
Moved to `pm2 start server.js` i'll monitor how it will be work!
