### ISSUE TITLE
Add driver for libmdbx

### ISSUE THREAD

**Issue by leo-yuriev** [fastogt/fastonosql#36]
https://github.com/leo-yuriev/libmdbx

@topilski, please assign this issue to me.
regards.

**Comment by topilski** [comment]
Sure, will wait your implementation, fill free to ask questions!

**Comment by leo-yuriev** [comment]
pending...

**Comment by topilski** [comment]
Hi, pending what?

**Comment by erthink** [comment]
> Sure, will wait your implementation, fill free to ask questions!

I tried several times to build fastonosql to implement a driver for the [libmdbx](https://github.com/erthink/libmdbx).
So, I may be stupid for build fastnosql from a sources, but I can't call your CMake scripts full-fledged or successful, and python scripts look for me like terrible unacceptable crutches.

**Comment by erthink** [comment]
https://www.opennet.ru/openforum/vsluhforumID3/122544.html#74

**Comment by topilski** [comment]
Некрасиво разговариваете чтоб вам отвечать.
