### ISSUE TITLE
memcached on Windows: Not connected to server, impossible to get discovery info

### ISSUE THREAD

**Issue by ZaneCEO** [fastogt/fastonosql#4]
Hi,
I just found your interesting project and I'm playing around a bit. I'm trying to connect to locally-installed memcached instance on Windows.

When I create a new connection with `-h localhost -p 11211 -d \n` it tests ok but then, when I select `Connect/disconnect` I get:

`Not connected to server, impossible to get discovery info!`

The service runs ok:

````
telnet 127.0.0.1 11211
stats

STAT pid 1500
STAT uptime 10563
STAT time 1459244697
STAT version 1.4.5_4_gaa7839e
STAT pointer_size 32
STAT curr_connections 31
STAT total_connections 39
STAT connection_structures 33
STAT cmd_get 283
STAT cmd_set 29
STAT cmd_flush 0
STAT get_hits 256
STAT get_misses 27
STAT delete_misses 0
STAT delete_hits 0
STAT incr_misses 0
STAT incr_hits 0
STAT decr_misses 0
STAT decr_hits 0
STAT cas_misses 0
STAT cas_hits 0
STAT cas_badval 0
STAT auth_cmds 0
STAT auth_errors 0
STAT bytes_read 64803
STAT bytes_written 444631
STAT limit_maxbytes 67108864
STAT accepting_conns 1
STAT listen_disabled_num 0
STAT threads 4
STAT conn_yields 0
STAT bytes 51888
STAT curr_items 28
STAT total_items 29
STAT evictions 0
STAT reclaimed 0
END
````

what am I missing?

Thanks!

**Comment by topilski** [comment]
@ZaneCEO thank you for this issue, bug was fixed and in next release you can use Memcached on Windows system without problems. Fix you can find here: https://github.com/fastogt/fastonosql/commit/3ec55f0cacf2ced6e9ac5073852323923b91c11c , also if you want i can attach installer with fixes especially for you! thank you for using FastoNoSQL.

**Comment by ZaneCEO** [comment]
Hi, thanks for your reply. I'm in no hurry, I'll just wait for the next release.
