### ISSUE TITLE
Are there any plans to support zookeeper?

### ISSUE THREAD

**Issue by fengyunhe** [fastogt/fastonosql#41]
thank you very much for this software. I like this software very much. I hope it will be better

**Comment by topilski** [comment]
Hi @fengyunhe thank you, now not supported, can you provide more information about "zookeeper".

**Comment by fengyunhe** [comment]
ZooKeeper is simple. ZooKeeper allows distributed processes to coordinate with each other through a shared hierarchal namespace which is organized similarly to a standard file system. The name space consists of data registers - called znodes, in ZooKeeper parlance - and these are similar to files and directories. Unlike a typical file system, which is designed for storage, ZooKeeper data is kept in-memory, which means ZooKeeper can achieve high throughput and low latency numbers.

The name space provided by ZooKeeper is much like that of a standard file system. A name is a sequence of path elements separated by a slash (/). Every node in ZooKeeper's name space is identified by a path.

more info in https://zookeeper.apache.org/doc/trunk/zookeeperOver.html

**Comment by topilski** [comment]
@fengyunhe do you know some C/C++ client api for it?

**Comment by fengyunhe** [comment]
This is C client source : [C client source](https://github.com/apache/zookeeper/tree/master/src/c)

**Comment by topilski** [comment]
Hi @fengyunhe , i think we can integrate Zookeeper into FastoNoSQL. Do you know some gui tools for Zookeeper?

**Comment by topilski** [comment]
ping

**Comment by topilski** [comment]
No
