### ISSUE TITLE
Crash on ubuntu 16.04 when running transaction on Redis

### ISSUE THREAD

**Issue by ozomer** [fastogt/fastonosql#42]
I tried to run a simple transaction on my Redis server:
```
MULTI
INCR a
EXEC
```
and the program crashed with Segmentation fault.
Using FastoNoSql 1.7.1.0 ( 64 BIT DEBIAN/UBUNTU 1.7.1 PACKAGE (.DEB) ) on Ubuntu 16.04.
I don't know where to find error logs.

**Comment by topilski** [comment]
Hi @ozomer , thank you for issue will try to reproduce.

**Comment by topilski** [comment]
Fixed, but need to implement properly handling result of MULTI commands.

**Comment by ozomer** [comment]
Great, waiting for the next deb release. Awesome project, btw :+1:

**Comment by topilski** [comment]
@ozomer thank you, release will be tomorrow, we working for you!
