### ISSUE TITLE
CONFIG GET does not work

### ISSUE THREAD

**Issue by ozomer** [fastogt/fastonosql#43]
config get * fails: "ERR wrong number of arguments for 'GET' command" - probably tries to parse it as a GET command, not as CONFIG GET.

Using FastoNoSQL 1.8.0.0 from deb on Ubuntu 16.04

**Comment by topilski** [comment]
Hi @ozomer , thank you for issue will try to reproduce.

**Comment by topilski** [comment]
Fixed, very big thank you for this bug, it was critical issue(all double words commands in Redis didn't work). I will do new release tomorrow.
