### ISSUE TITLE
Unable to launch on Mac because developer unidentified

### ISSUE THREAD

**Issue by florian-koenig** [fastogt/fastonosql#44]
As of recently, Mac OS prevents me from opening FastoNoSQL.app with the following message:

> "FastoNoSQL" can't be opened because it is from an unidentified developer. Your security preferences allow installation of only apps from the Mac App Stroe and identified developers.

This happens on **Mac OS X El Capitan (10.11.6)** with **fastonosql-1.8.0-x86_64.dmg**. There is a work-around (https://support.apple.com/kb/PH25088?locale=en_US) but it would be great to be able to use the app without jumping through hoops.

**Comment by topilski** [comment]
HI, very interesting will try to patch.

**Comment by florian-koenig** [comment]
Thank you @topilski for the quick response!

**Comment by topilski** [comment]
You are welcome!

**Comment by topilski** [comment]
Hi @florian-koenig we ready to buy certificate, can you help me with it? Or someone else? Which certificate i should by? and how to sign packages?

**Comment by topilski** [comment]
Fixed!
