### ISSUE TITLE
Support for MS Extensible Storage Engine (ESE)

### ISSUE THREAD

**Issue by MedAnd** [fastogt/fastonosql#48]
Any plans to support MS [Extensible Storage Engine ](https://msdn.microsoft.com/en-us/library/gg269259(v=exchg.10).aspx) / [Extensible Storage Engine Reference](https://msdn.microsoft.com/en-us/library/office/gg269245(v=exchg.10).aspx)

**Comment by topilski** [comment]
Hi, do you know some C/C++ client api for this technology?

**Comment by MedAnd** [comment]
Hi @topilski, not sure if this helps: [ESENT Managed Interop](https://github.com/Microsoft/ManagedEsent)
