### ISSUE TITLE
Leveldb does not show tables/data

### ISSUE THREAD

**Issue by nicolas-raoul** [fastogt/fastonosql#5]
I opened a LevelDB folder that contains data for sure.

PROBLEM: No data is shown:

![](http://i.imgur.com/ZhefRWX.png)

I clicked on all buttons/options, nothing show any data.
##

**Comment by topilski** [comment]
Good day @nicolas-raoul , is logs contains any errors?

**Comment by nicolas-raoul** [comment]
Thank you for the quick reply! As seen in the screenshot above, nothing appear in the Logs tab, even with log enabled and set to level 0 or 10000.

**Comment by topilski** [comment]
can't reproduce your bug, can you send your db to my email? atopilski@gmail.com

**Comment by topilski** [comment]
Hi @nicolas-raoul , please try to reproduces this issue in new version of FastoNoSQL.

**Comment by topilski** [comment]
ping

**Comment by nicolas-raoul** [comment]
I am unfortunately unable to test due to #13 and #14, but anyone can test easily by installing Chrome and any Chrome extension.
Thanks! :-)

**Comment by topilski** [comment]
Fixed in version 1.1.0 please check behavior and close issue if work as needed.

**Comment by topilski** [comment]
ping
