### ISSUE TITLE
Signup section on https://fastonosql.com/signup not working

### ISSUE THREAD

**Issue by lflserg** [fastogt/fastonosql#51]
That makes impossible to proceed with using your tool without building it:)

**Comment by lflserg** [comment]
Also in the build section for windows next step gives an error
$ /usr/bin/python3 build_env.py
Traceback (most recent call last):
  File "build_env.py", line 6, in <module>
    from pybuild_utils.base import run_command
ImportError: No module named 'pybuild_utils.base'

**Comment by topilski** [comment]
Hi @lflserg thank you for issue, why signup not working? Which error you revived?

**Comment by topilski** [comment]
To resolve python issue please execute `git submoule update --init --recursive`, pybuild_utils it is submodule.

**Comment by lflserg** [comment]
@topilski  thank you now when i went to the page it showed that confirmation letter was sent. Seems like some server issues. Didnt track the error though(( But the process was very long..... Several minutes of watching the spinner

**Comment by lflserg** [comment]
@topilski  now it`s 
$ /usr/bin/python3 build_env.py
Traceback (most recent call last):
  File "build_env.py", line 367, in <module>
    request = BuildRequest(platform_str, arch_bit_str, 'build_' + platform_str + '_env')
  File "build_env.py", line 35, in __init__
    raise utils.BuildError('invalid platform')
pybuild_utils.base.utils.BuildError: invalid platform

**Comment by topilski** [comment]
@lflserg did you receive confirm message? you also should apply your email. If you want i can remove your email from db, and you can try to re sugnup.

**Comment by topilski** [comment]
Also which platform you using for build?

**Comment by topilski** [comment]
I think you didn't confirm your email, without confirm you can't login.

**Comment by lflserg** [comment]
@topilski  Yes, i received it but from the third try. So when i clicked sign up it took several minutes for page to react

**Comment by lflserg** [comment]
@topilski seems like platform is not recognized trying to build in MSYS on Windows, what parameters are better to send?

**Comment by topilski** [comment]
Hi @lflserg i removed your email from our FastoNoSQL db, please re signup. To do build for windows is very hard, but if you want i can help you. First of all you need to download msys2 link here: http://www.msys2.org/ , via pacman install qt, and after that execute build_env.py script. But you should understand that qt on our server build from sources and as result qt library optimized more extremely.

**Comment by lflserg** [comment]
@topilski  I see the guide https://github.com/fastogt/fastonosql/wiki/Build
But it might miss some steps as build_env.py does not recognize my system (platform_str is undefined) so i suppose i have to pass some params in there but dont know in what format.

 I am trying to build the app because i have some data and i wonder if the app can open it (which I am unsure about) and it would be a waste if i bought it and failed to open desired data.

**Comment by topilski** [comment]
@lflserg agree with you, which database you want to open? But you also should understand me, because i write this program about 3 years alone, without support of db maintainers, and i don't like to see how user start application about 300-500 times and don't want to pay. 3-4$ it is not a huge amount of money only for this purposes i created subscription i want that application grow up, i want to hire web developers, QA engineers, now this all stuff i do after my primary work. 

execute next command: `python3 build_env.py windows x86_64` , also please use /usr/mingw64/bin/python3 (should be native msys python).

**Comment by lflserg** [comment]
@topilski  504 Gateway Time-out :(

I want to open LevelDB, i am new to it so i suppose i have to play with lots of options - separators, comparators and stuff and it might not be opened:)

**Comment by topilski** [comment]
I see you in our db, you can sign in. What about python script, did you try to build environment?

**Comment by topilski** [comment]
Hi @lflserg , i sent you zip archive via email, please test application, i'am waiting your feedback.

**Comment by lflserg** [comment]
@topilski thank you. I see you support indexed db and that feature was lacking in other competitors I tried, cool. But like I said I am new to this and after opening indexed db i have something like this for keys: 
"����
o"pId"en:es::A"id"en:es:a"phrase"A"translationsaI"
Will keep playing with delimiters and stuff, or from your opinion its something wrong with database itself?

**Comment by topilski** [comment]
I need to recheck index_db, and after that answer on your question.

**Comment by topilski** [comment]
I checked, yes worked, implementation i took from chromium.
