### ISSUE TITLE
How to support redis cluster?

### ISSUE THREAD

**Issue by superwen0001** [fastogt/fastonosql#52]
How to support redis cluster?

**Comment by topilski** [comment]
Hi @superwen0001 , you need to create cluster connection after that discover this connection.

**Comment by superwen0001** [comment]
When I get a key on one of the other nodes, return to me nil,Set a key to remind me to move., what should I do to fit the cluster of multiple nodes? @topilski

**Comment by topilski** [comment]
Yes it is, because i don't know how to implement redirection to other node in cluster. I will think about it, how more gracefully implement it.

**Comment by superwen0001** [comment]
That's not very good. When I get a key on another node, it's nil, and you should consider opening a new connect directly to execute.

**Comment by superwen0001** [comment]
thank you,Waiting for your new implementation.For the time being, the support for cluster is not friendly enough.

**Comment by topilski** [comment]
Hi @superwen0001, i implemented redirection to nodes in cluster mode.
![image](https://user-images.githubusercontent.com/4686379/35208081-80bd610c-ff57-11e7-8ff4-c3156b6b2ef1.png)
