### ISSUE TITLE
Please don't spam random email addresses

### ISSUE THREAD

**Issue by eXpl0it3r** [fastogt/fastonosql#54]
I've received three cold emails about this project. I haven't signed up for anything and I do not appreciate being spammed. All the emails have been reported as spam and will be reported as abuse to the mail servers.

**Comment by topilski** [comment]
Don't spam here please.

**Comment by topilski** [comment]
We using only https://mailerlite.com and we have paid account. All other messages not from us.

**Comment by eXpl0it3r** [comment]
Then tell your "friend" (aka marketing guy, aka shady agency you told to get you some website views) to stop spamming people.

You see my address at the bottom of the image and I'm pretty sure that was the same mailchimp setup I've received the other emails from.

![image](https://user-images.githubusercontent.com/920861/36077006-ea2bfa46-0f64-11e8-8d21-f11a94ce7029.png)

**Comment by topilski** [comment]
Unfortunately we don't know what you are talking about.

**Comment by eXpl0it3r** [comment]
Unfortunately I don't really believe you, but I'd still recommend you get in contact with MailChimp to get this person to stop spamming people. It hurts your product directly, as people who receive the spam emails will forever associate your product name with spam and scams.
