### ISSUE TITLE
When opening a RocksDB I get an no locks available error

### ISSUE THREAD

**Issue by jo-tud** [fastogt/fastonosql#57]
`00:03:06.330: Fail open database: IO error: While lock file: /db/LOCK: No locks available!`
This happens regardless of whether there is a LOCK file in the directory or not.

**Comment by topilski** [comment]
Hi @jo-tud , i need to check.

**Comment by topilski** [comment]
Hi @jo-tud , may be it is your issue: https://stackoverflow.com/questions/37310588/rocksdb-io-error-lock-no-locks-available ?

**Comment by topilski** [comment]
ping
