### ISSUE TITLE
Registration on website is broken and common.git is missing

### ISSUE THREAD

**Issue by mattkanwisher** [fastogt/fastonosql#58]
I tried to buy on your website and your website never registers my users, and you code cant compile cause you clearly removed one of the GitHub repos. 

https://github.com/fastogt/common.git

**Comment by topilski** [comment]
Hi, common is private repository. My confirms email moving into spam folder?

**Comment by topilski** [comment]
According logs, email was send, you can confirm it.

**Comment by topilski** [comment]
I registered your email, please tru to singin.

**Comment by mattkanwisher** [comment]
emails came in eventually.

**Comment by topilski** [comment]
all worked? do you have some issues?

**Comment by topilski** [comment]
Hi @mattkanwisher , i opened common, i want that my project will be full opensource. I am ashamed, thank you!
