### ISSUE TITLE
RocksDB: Load content of database doesn't work

### ISSUE THREAD

**Issue by melnikaite** [fastogt/fastonosql#59]
I pointed FastNoSQL to the folder of Parity database and successfully connected to the RocksDB. Then I do right click to connection name and pressed Load Databases.
It added `col0 (0/0)` ... `col7 (0/0)`
It doesn't look realistic for 14 gigabyte folder with database

**Comment by topilski** [comment]
Hi, please do screenshot, i want to see your keys? Also try dbcount command to see how many keys in your database.

**Comment by melnikaite** [comment]
![fastonosql 1 17 4 0 2018-05-08 19-45-06](https://user-images.githubusercontent.com/900724/39770701-6fcdbe56-52f8-11e8-9b56-835f9df16c4d.png)

**Comment by topilski** [comment]
Thank you, please select needed database and press load content. According screen default db selected. Please try other.

**Comment by topilski** [comment]
Right click => 'set default' on db

**Comment by melnikaite** [comment]
You are right
I had to Set default, wait some time and when it become red try to load content. The same workaround for getting value.

**Comment by topilski** [comment]
'Set default' functionality works immediately but red rendering after redraw screen.

**Comment by topilski** [comment]
Hi @melnikaite , we can close this issue?

**Comment by melnikaite** [comment]
Yes, shure

сб, 12 мая 2018 г., 18:15 Alexandr Topilski <notifications@github.com>:
