### ISSUE TITLE
Crash application on running "Discovery" under Sentinel Connection

### ISSUE THREAD

**Issue by Trane9991** [fastogt/fastonosql#6]
The same issue as with fastoredis
https://github.com/fastogt/fastoredis/issues/62

application crashes on Windows x64 when creating Sentinel Connection and pushing "Discovery" button.

Please ask for details that I can provide for you.

Regards, Taras.

**Comment by topilski** [comment]
Good day, please specify logs which you have.

**Comment by Trane9991** [comment]
I can't see any logs in the ~/.config/FastNoSQL, only config.ini file.

**Comment by topilski** [comment]
Do you have $HOME/FastNoSQL.log file?

**Comment by Trane9991** [comment]
No, there is no such file in the _C:/User/<Username>_ (I believe this is $HOME on Windows)

**Comment by topilski** [comment]
Yes you right, is this ssh connection?

**Comment by Trane9991** [comment]
No, direct connection.

**Comment by topilski** [comment]
Please specify your email i will send you new FastoNoSQL build, this build save logs to file.

**Comment by Trane9991** [comment]
@topilski just send you a mail to the address from your GitHub profile.

**Comment by topilski** [comment]
Resolved by email, fix here: 0d6a1a8069d64fc82c8c51dcd23add86360fce07
