### ISSUE TITLE
I can not connect to a level

### ISSUE THREAD

**Issue by marcelovieiratecnologia** [fastogt/fastonosql#60]
I'm trying to connect to a file. "ldb", so you understand better is a virtual currency file specifically DashCoin and it's written the blocks in my local machine and .ldb file formats and it's just the one I do not have access to!

**Comment by marcelovieiratecnologia** [comment]
has the github https://github.com/techsolutions-ltd/dascoin-blockchain, but the tests would be by RPC and not locally.

to do the actual test I intend to be installing the portfolio expecting it to sync and checking in the% appdata% / DashCoin files directory

**Comment by topilski** [comment]
Hi @marcelovieiratecnologia , i updated leveldb driver can you try connect again?
