### ISSUE TITLE
Building prefix should not be /usr/local by default without sudo

### ISSUE THREAD

**Issue by XVilka** [fastogt/fastonosql#70]
If you follow https://github.com/fastogt/fastonosql/wiki/Build instructions it by default tries to install into `/usr/local` on Linux and doesn't asking for sudo.
The best option is to use `~/.local/bin` by default if the user is not root: https://unix.stackexchange.com/questions/316765/which-distributions-have-home-local-bin-in-path

**Comment by topilski** [comment]
Hey, some libraries should be in /usr/local

**Comment by XVilka** [comment]
For CMake, there’s CMAKE_INSTALL_PREFIX:
```
$ cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local ..
```

**Comment by topilski** [comment]
Cool but not interesting.

**Comment by XVilka** [comment]
See also https://stackoverflow.com/questions/12075371/cmake-find-library-custom-library-location
