### ISSUE TITLE
Can only type 2 / (slash) in the path

### ISSUE THREAD

**Issue by danielepolencic** [fastogt/fastonosql#8]
When I type the path of the database (any) I can only type 2 slashes in the path:

![image](https://cloud.githubusercontent.com/assets/1130499/19384255/4a2dcb6a-9200-11e6-9917-8dc006a7389b.png)

after the second `/` I'm not able to type any other character. I'm on MacOSX 10.10.5

```
FastoNoSQL 0.7.3.0
Revision:dac05fb
```
##

**Comment by topilski** [comment]
Hi thank you, trying to reproduce.
