### ISSUE TITLE
Chrome says certificate expired for: https://fastonosql.com

### ISSUE THREAD

**Issue by selangley-wa** [fastogt/fastonosql#80]
If I attempt to go to the referenced web site: https://fastonosql.com

Google Chrome says the certificate has expired.  Are you aware of this?

![image](https://user-images.githubusercontent.com/43478262/74252210-2953eb80-4ca2-11ea-860d-6861c99d22f5.png)

**Comment by topilski** [comment]
Fixed, thank you
