### ISSUE TITLE
Failed to start on manjaro gnome，Can it be packaged as appimage？

### ISSUE THREAD

**Issue by mirroro** [fastogt/fastonosql#81]
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
./fastoredis：行 15: 12746 已放弃               （核心已转储）"$SOURCE_DIR/FastoRedis" $

**Comment by FelipeAzambuja** [comment]
i have same problem in fedora 38
