### ISSUE TITLE
Error build_env fastonosql on windows

### ISSUE THREAD

**Issue by jurepetrovic** [fastogt/fastonosql#85]
Hello, 

I tried building fastonosql on win7, x64 environment. 
Got msys2 64-bit and is giving me this error, when trying to extract openssl

Any ideas? 

![image](https://user-images.githubusercontent.com/35005863/147256836-43354b9f-7b57-43f1-a728-b59574a52013.png)

Thanks a million, 
Jure

**Comment by fengkongling** [comment]
ok，亲~~~

**Comment by jurepetrovic** [comment]
Hello @fengkongling, 

I don't understand. What do you mean? Are you just joking here? 

Rgds, 
Jure

**Comment by haogeek** [comment]
Same problem here. I think the developer does not really want to care and fix this, sadly.

**Comment by topilski** [comment]
I think this software is paid, you can download builds from website: https://fastonosql.com/pro_users_downloads
